### PR TITLE
Fix Yolov5 for TensorRT 8 support

### PR DESCRIPTION
**Pull request by adujardin**
Tested with TRT 8.0 EA and TRT 7.2 (to validate retro compatibility)

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@adujardin  Thanks for the PR.

Will it report compile error if there is no `noexcept` for trt 8.0 EA?

**Comment by adujardin** [comment]
Yes, with trt 8 these functions use `noexcept`, breaking the inheritance, with error like : 

`tensorrtx/yolov5/yololayer.h(87): error: exception specification for virtual function "nvinfer1::YoloLayerPlugin::detachFromContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::detachFromContext"`

I'm not sure why they changed, I noticed that 7.2 used `TRTNOEXCEPT` in the trt headers

**Comment by wang-xinyu** [comment]
@adujardin ok, this is helpful. But let's wait for trt8.0 release version not EA.

**Comment by research-boy** [comment]
This commit works fine with both trt8 and trt7.2

**Comment by ammaddd** [comment]
This PR works!!
Screenshot from 2021-06-28 19-07-27

**Comment by adujardin** [comment]
Just a heads up now that TRT 8.0 GA is released, I tested this PR with it and it's working as expected :slightly_smiling_face:
